### DISCUSSION TITLE
Huly and Nginx Proxy Manager

### DISCUSSION THREAD

**Discussion by dauphinpasdroit** [hcengineering/platform#6857] [Architecture]
Hello everyone,

I'm self-hosting a huly instance on a proxmox host. I would like to publish it using dns domain name.

I use Nginx Proxy Manager to reverse proxy, get a certificate etc... in front of the huly instance.

When I try to access my huly instance, I get the error:

`Unknow error: NetworkError when attempting to fetch resource.`

![image](https://github.com/user-attachments/assets/92c8021d-60f6-4272-b1c1-f763b7217380)

I use this repository to deploy the instance: https://github.com/hcengineering/huly-selfhost

And the docker is basically the same as the one in the repo:

```
version: "3"
services:
  mongodb:
    image: "mongo:7-jammy"
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  minio:
    image: "minio/minio"
    command: server /data --address ":9000" --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - files:/data
    restart: unless-stopped
  elastic:
    image: "elasticsearch:7.14.2"
    command: |
      /bin/sh -c "./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;
      /usr/local/bin/docker-entrypoint.sh eswrapper"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - BITNAMI_DEBUG=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8082
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    restart: unless-stopped
  account:
    image: hardcoreeng/account:v0.6.313
    links:
      - mongodb
      - minio
    ports:
      - 3000:3000
    environment:
      - SERVER_PORT=3000
      - SERVER_SECRET=***
      - MONGO_URL=mongodb://mongodb:27017
      - TRANSACTOR_URL=ws://transactor:3333;ws://10.10.1.11:3333
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - FRONT_URL=http://front:8080
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http://10.10.1.11:3000
      - ACCOUNT_PORT=3000
    restart: unless-stopped
  workspace:
    image: hardcoreeng/workspace:v0.6.313
    links:
      - mongodb
      - minio
    environment:
      - SERVER_SECRET=***
      - MONGO_URL=mongodb://mongodb:27017
      - TRANSACTOR_URL=ws://transactor:3333;ws://10.10.1.11:3333
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http://account:3000
      - NOTIFY_INBOX_ONLY=true
    restart: unless-stopped
  front:
    image: hardcoreeng/front:v0.6.313
    links:
      - mongodb
      - minio
      - elastic
      - collaborator
      - transactor
    ports:
      - 8087:8080
    environment:
      - SERVER_PORT=8080
      - SERVER_SECRET=***
      - ACCOUNTS_URL=http://10.10.1.11:3000
      - REKONI_URL=http://10.10.1.11:4004
      - CALENDAR_URL=http://10.10.1.11:8095
      - GMAIL_URL=http://10.10.1.11:8088
      - TELEGRAM_URL=http://10.10.1.11:8086
      - UPLOAD_URL=/files
      - ELASTIC_URL=http://elastic:9200
      - COLLABORATOR_URL=ws://10.10.1.11:3078
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - MONGO_URL=mongodb://mongodb:27017
      - TITLE=Huly Self Hosted
      - DEFAULT_LANGUAGE=en
      - LAST_NAME_FIRST=true
    restart: unless-stopped
  collaborator:
    image: hardcoreeng/collaborator:v0.6.313
    links:
      - mongodb
      - minio
      - transactor
    ports:
      - 3078:3078
    environment:
      - COLLABORATOR_PORT=3078
      - SECRET=***
      - ACCOUNTS_URL=http://account:3000
      - MONGO_URL=mongodb://mongodb:27017
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
    restart: unless-stopped
  transactor:
    image: hardcoreeng/transactor:v0.6.313
    links:
      - mongodb
      - elastic
      - minio
      - account
    ports:
      - 3333:3333
    environment:
      - SERVER_PORT=3333
      - SERVER_SECRET=***
      - SERVER_CURSOR_MAXTIMEMS=30000
      - ELASTIC_URL=http://elastic:9200
      - ELASTIC_INDEX_NAME=huly_storage_index
      - MONGO_URL=mongodb://mongodb:27017
      - METRICS_CONSOLE=false
      - METRICS_FILE=metrics.txt
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - REKONI_URL=http://rekoni:4004
      - FRONT_URL=http://10.10.1.11:8087
      - ACCOUNTS_URL=http://10.10.1.11:3000
      - LAST_NAME_FIRST=true
    restart: unless-stopped
  rekoni:
    image: hardcoreeng/rekoni-service:v0.6.313
    ports:
      - 4004:4004
    environment:
      - SECRET=***
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped
volumes:
  db:
  files:
  elastic:
  etcd:
```

The only difference with the installation documentation is that I didn't run an nginx on the server where the huly instance is hosted.

I wanted to use my pre existing nginx proxy manager instead.

Thank you for your help
